### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by mmm545** [AkmalFairuz/packencryptor#1]
you shall delete dis

**Comment by PrograMistV1** [comment]
Why?

**Comment by Buddelbubi** [comment]
https://www.virustotal.com/gui/file/b1f2800c79bf3a130d5594cbd76ce8d81f0e3ac458b94fb64c35e18852fc9906 ???

**Comment by AkmalFairuz** [comment]
> https://www.virustotal.com/gui/file/b1f2800c79bf3a130d5594cbd76ce8d81f0e3ac458b94fb64c35e18852fc9906 ???

this software is open source, you can compile by yourself, also virustotal is not accurate
